### ISSUE TITLE
Where is the project documentation?

### ISSUE THREAD

**Issue by mik01aj** [Adslot/alexandria#116]
This looks like a cool library. Where can I find docs for it?

If you need a tool for documenting react components, you can try [react-styleguidist](https://github.com/sapegin/react-styleguidist).

**Comment by camjc** [comment]
Hey @mik01aj ,

Thanks for the feedback!

Up until now we've found the components to be quite self documenting,
especially with the examples (shown when you `npm run start`),
and with 100% PropTypes and test coverage.

That looks like an interesting package though,
so I'll take a look into it and other options within the next fortnight.

Cheers,
- Cam

**Comment by camjc** [comment]
For now I don't want to over-complicate the build with a heavy tool like react-styelguidist, so for now the examples at `npm start` are sufficient for our project goals.
We will continue to follow this and hopefully set up a url where you can view the examples.
